<?php
/**
 * Functions.php contains all the core functions for your theme to work properly.
 * Please do not edit this file!!
 *
 * @package Tetris WordPress Theme
 * @since 1.0
 * @author AJ Clarke : http://wpexplorer.com
 * @copyright Copyright (c) 2012, AJ Clarke
 * @link http://wpexplorer.com
 * @license http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */
 
 
/**
* Define Constants
*/
define( 'WPEX_JS_DIR', get_template_directory_uri().'/js' );
define( 'WPEX_CSS_DIR', get_template_directory_uri().'/css' );


/* adding svg upload on media library */
    function custom_mtypes( $m ){
        $m['svg'] = 'image/svg+xml';
        $m['svgz'] = 'image/svg+xml';
        return $m;
    }
    add_filter( 'upload_mimes', 'custom_mtypes' );




/*
 * Helper function to return the theme option value. If no value has been saved, it returns $default.
 * Needed because options are saved as serialized strings.
 *
 * This code allows the theme to work without errors if the Options Framework plugin has been disabled.
 * @since Authentic Corp 1.0
 */
if ( !function_exists( 'of_get_option' ) ) {
	function of_get_option($name, $default = false) {
		$optionsframework_settings = get_option('optionsframework');
		// Gets the unique option id
		$option_name = $optionsframework_settings['id'];
		if ( get_option($option_name) ) {
			$options = get_option($option_name);
		}
		if ( isset($options[$name]) ) {
			return $options[$name];
		} else {
			return $default;
		}
	}
}

/**
* Get functions
* @since 1.0
*/

// TGM Plugin Activation => https://github.com/thomasgriffin/TGM-Plugin-Activation
require_once ( get_template_directory() .'/functions/recommend-plugins.php' );

// Add basic hooks
require_once ( get_template_directory() .'/functions/hooks.php' );

// Load CSS and JS
require_once( get_template_directory() .'/functions/scripts.php' );

// Define widget areas and add custom widgets
require_once( get_template_directory() .'/functions/widget_areas.php' );
require_once( get_template_directory() .'/functions/widget_social.php' );

// Setup some useful functions
require_once( get_template_directory() .'/functions/font_awesome.php' );
require_once( get_template_directory() .'/functions/pagination.php' );
require_once( get_template_directory() .'/functions/img_resizer.php' );
require_once( get_template_directory() .'/functions/img_defaults.php' );
require_once( get_template_directory() .'/functions/wpex_comments_output.php' );

//load these functions only in the admin dashboard
if( defined('WP_ADMIN') && WP_ADMIN ) {
	require_once( get_template_directory() .'/functions/post_meta.php' );	
}

/**
* Theme Setup
*/

// Add Post Formats Support
add_theme_support( 'post-formats', array( 'video', 'quote', 'link', 'audio', 'image', 'gallery', 'atelier' ) );

//Localization support
load_theme_textdomain( 'wpex', get_template_directory() .'/lang' );

function wpex_setup() {

	//default width of primary content area
	$content_width = 970;
	
	//theme support
	add_theme_support('automatic-feed-links');
	add_theme_support('custom-background');
	add_theme_support('post-thumbnails');
	
	//register navigation menus
	if ( ! function_exists ( 'wpex_register_nav_menus' ) ) {
		function wpex_register_nav_menus ( ) {
			$wpex_menus = array(
				'main_menu' => __( 'Main', 'wpex' )
			);
			$wpex_menus = apply_filters ( 'wpex_nav_menus', $wpex_menus );
			register_nav_menus ( $wpex_menus );
		}
	}
	wpex_register_nav_menus();

}
add_action( 'after_setup_theme', 'wpex_setup' );


/**
* Replace Soliloquy affilate
* @since 1.0
*/
add_filter( 'tgmsp_affiliate_url', 'test_affiliate_url' );
function test_affiliate_url() {
	return 'http://www.wpexplorer.com/soliloquy-wordpress-plugin';
}

/**
* Change default read more style
* @since 1.0
*/
if ( !function_exists( 'wpex_new_excerpt_more' ) ) :
	function wpex_new_excerpt_more($more) {
		global $post;
		return '...';
	}
	add_filter('excerpt_more', 'wpex_new_excerpt_more');
endif;


/**
* Add home page option to WordPress Menu
* @since 1.0
*/
add_filter( 'wp_page_menu_args', 'home_page_menu_args' );
function home_page_menu_args( $args ) {
	$args['show_home'] = true;
	return $args;
}


/**
* Define Social Options For This Theme
* @since 1.0
*/
function wpex_get_social() {
	
	//define array of icons
	$social_icons = array(
			'addThis' => 'addThis',
			'behance' => 'behance',
			'blogger' => 'blogger',
			'delicious' => 'delicious',
			'deviantart' => 'deviantart',
			'digg' => 'digg',
			'dopplr' => 'dopplr',
			'dribbble' => 'dribbble',
			'evernote' => 'evernote',
			'facebook' => 'facebook',
			'flickr' => 'flickr',
			'forrst' => 'forrst',
			'gitHub' => 'gitHub',
			'google' => 'google',
			'grooveshark' => 'grooveshark',
			'instagram' => 'instagram',
			'lastfm' => 'lastfm',
			'linkedin' => 'linkedin',
			'myspace' => 'myspace',
			'pinterest' => 'pinterest',
			'paypal' => 'paypal',
			'picasa' => 'picasa',
			'pinterest' => 'pinterest',
			'posterous' => 'posterous',
			'reddit' => 'reddit',
			'sharethis' => 'sharethis',
			'skype' => 'skype',
			'soundcloud' => 'soundcloud',
			'spotify' => 'spotify',
			'stumbleupon' => 'stumbleupon',
			'tumblr' => 'tumblr',
			'twitter' => 'twitter',
			'viddler' => 'viddler',
			'vimeo' => 'vimeo',
			'virb' => 'virb',
			'windows' => 'windows',
			'wordPress' => 'wordPress',
			'youtube' => 'youtube',
			'zerply' => 'zerply',
			'rss' => 'rss',
			'mail' => 'mail' );
	
	//return array
	return apply_filters('wpex_get_social', $social_icons);
}


/*-----------------------------------------------------------------------------------*/
// adding custom post type - mission
/*-----------------------------------------------------------------------------------*/

// Custom post type = missions - déclaration du type 
function outils_post_type() {

    $labels = array(
        'name' => _x('Outils', 'post type general name'),
        'singular_name' => _x('Outil', 'post type singular name'),
        'add_new' => _x('Ajout', 'outil'),
        'add_new_item' => __('Ajout d\'un nouvel outil'),
        'edit_item' => __('Modifier un outil'),
        'new_item' => __('Ajouter un outil'),
        'view_item' => __('Voir l\'outil'),
        'search_items' => __('Chercher un outil'),
        'not_found' =>  __('Aucun outil n\'a été trouvé'),
        'not_found_in_trash' => __('Aucun outil de trouvé dans la poubelle'),
        'parent_item_colon' => ''
    );
  $args = array(
        'labels' => $labels,
        'public' => true,
        'publicly_queryable' => true,
        'show_ui' => true,
        'query_var' => true,
        'rewrite' => array( 'slug' => 'outil','with_front' => false),
        'capability_type' => 'post',
        'has_archive' => true,
        'hierarchical' => false,
        'menu_position' => 5,
        'supports' => array('title','editor','thumbnail'),
        'taxonomies' => true,
        'can_export'=> true,  
    );
    register_post_type('outils',$args);
    
}

add_action( 'init', 'outils_post_type' );



function mission_post_type() {

    $labels = array(
        'name' => _x('Missions', 'post type general name'),
        'singular_name' => _x('Mission', 'post type singular name'),
        'add_new' => _x('Add New', 'mission'),
        'add_new_item' => __('Add New Mission'),
        'edit_item' => __('Edit Misson'),
        'new_item' => __('New Mission'),
        'view_item' => __('View Mission'),
        'search_items' => __('Search Missions'),
        'not_found' =>  __('No mission found'),
        'not_found_in_trash' => __('No mission found in Trash'),
        'parent_item_colon' => ''
    );
  $args = array(
        'labels' => $labels,
        'public' => true,
        'publicly_queryable' => true,
        'show_ui' => true,
        'query_var' => true,
        'rewrite' => array( 'slug' => 'mission','with_front' => false),
        'capability_type' => 'post',
        'has_archive' => true,
        'hierarchical' => false,
        'menu_position' => 5,
        'supports' => array('title','author','excerpt','editor','thumbnail','comments'),
        'taxonomies' => true,
        'can_export'=> true,  
    );
    register_post_type('missions',$args);
    
}

add_action( 'init', 'mission_post_type' );

// création de la taxonomie de mission 

function create_mission_taxonomy() {
// Add new taxonomy, make it hierarchical (like categories)
	$labels = array(
		'name'              => _x( 'Types de missions', 'taxonomy general name' ),
		'singular_name'     => _x( 'Type de mission', 'taxonomy singular name' ),
		'search_items'      => __( 'Rechercher un type de mission' ),
		'all_items'         => __( 'Tous les types' ),
		'parent_item'       => __( 'Famille de mission' ),
		'parent_item_colon' => __( 'Famille:' ),
		'edit_item'         => __( 'Editer le type' ),
		'update_item'       => __( 'Mettre à jour le type' ),
		'add_new_item'      => __( 'Ajouter un nouveau type de mission' ),
		'new_item_name'     => __( 'Nom de ce type de mission' ),
		'menu_name'         => __( 'Type de mission' ),
	);

	$args = array(
		'hierarchical'      => true,
		'labels'            => $labels,
		'show_ui'           => true,
		'show_admin_column' => true,
		'query_var'         => true,
		'rewrite'           => array( 'slug' => 'ms','with_front' => FALSE),
	);

	register_taxonomy( 'type_mission', array( 'missions' ), $args );
    register_taxonomy_for_object_type( 'type_mission', 'missions' );
}

add_action( 'init', 'create_mission_taxonomy' );

/*-----------------------------------------------------------------------------------*/
// adding custom post type - formation
/*-----------------------------------------------------------------------------------*/

// Custom post type = formations - déclaration du type 

function formation_post_type() {

    $labels = array(
        'name' => _x('Formations', 'post type general name'),
        'singular_name' => _x('Formation', 'post type singular name'),
        'add_new' => _x('Add New', 'formation'),
        'add_new_item' => __('Add New Formation'),
        'edit_item' => __('Edit Formation'),
        'new_item' => __('New Formation'),
        'view_item' => __('View Formation'),
        'search_items' => __('Search Formations'),
        'not_found' =>  __('No formation found'),
        'not_found_in_trash' => __('No formation found in Trash'),
        'parent_item_colon' => ''
    );
  $args = array(
        'labels' => $labels,
        'public' => true,
        'publicly_queryable' => true,
        'show_ui' => true,
        'query_var' => true,
        'rewrite' => array( 'slug' => 'formation','with_front' => false),
        'capability_type' => 'post',
        'has_archive' => true,
        'hierarchical' => false,
        'menu_position' => 5,
        'supports' => array('title','author','excerpt','editor','thumbnail','comments'),
        'taxonomies' => true,
        'can_export'=> true,  
    );
    register_post_type('formations',$args);
    
}

add_action( 'init', 'formation_post_type' );

// création de la taxonomie type_formation

function create_formation_taxonomy() {
// Add new taxonomy, make it hierarchical (like categories)
	$labels = array(
		'name'              => _x( 'Types de formations', 'taxonomy general name' ),
		'singular_name'     => _x( 'Type de formation', 'taxonomy singular name' ),
		'search_items'      => __( 'Rechercher un type de formation' ),
		'all_items'         => __( 'Tous les types' ),
		'parent_item'       => __( 'Famille de formation' ),
		'parent_item_colon' => __( 'Famille:' ),
		'edit_item'         => __( 'Editer le type' ),
		'update_item'       => __( 'Mettre à jour le type' ),
		'add_new_item'      => __( 'Ajouter un nouveau type de formation' ),
		'new_item_name'     => __( 'Nom de ce type de formation' ),
		'menu_name'         => __( 'Type de formation' ),
	);

	$args = array(
		'hierarchical'      => true,
		'labels'            => $labels,
		'show_ui'           => true,
		'show_admin_column' => true,
		'query_var'         => true,
		'rewrite'           => array( 'slug' => 'form','with_front' => FALSE),
	);

	register_taxonomy( 'type_formation', array( 'formations' ), $args );
    register_taxonomy_for_object_type( 'type_formation', 'formations' );
}

add_action( 'init', 'create_formation_taxonomy' );


?>